% mens_dier_en_gezondheid
area_of_interest(21, mens_dier_en_gezondheid).
area_of_interest(24, mens_dier_en_gezondheid).
area_of_interest(43, mens_dier_en_gezondheid).
area_of_interest(47, mens_dier_en_gezondheid).
area_of_interest(117, mens_dier_en_gezondheid).

% mens_en_gedrag
area_of_interest(4, mens_en_gedrag).
area_of_interest(8, mens_en_gedrag).
area_of_interest(10, mens_en_gedrag).
area_of_interest(14, mens_en_gedrag).
area_of_interest(15, mens_en_gedrag).
area_of_interest(18, mens_en_gedrag).
area_of_interest(19, mens_en_gedrag).
area_of_interest(20, mens_en_gedrag).
area_of_interest(21, mens_en_gedrag).
area_of_interest(24, mens_en_gedrag).
area_of_interest(25, mens_en_gedrag).
area_of_interest(26, mens_en_gedrag).
area_of_interest(29, mens_en_gedrag).
area_of_interest(30, mens_en_gedrag).
area_of_interest(31, mens_en_gedrag).
area_of_interest(38, mens_en_gedrag).
area_of_interest(39, mens_en_gedrag).
area_of_interest(50, mens_en_gedrag).
area_of_interest(68, mens_en_gedrag).
area_of_interest(73, mens_en_gedrag).
area_of_interest(76, mens_en_gedrag).
area_of_interest(82, mens_en_gedrag).
area_of_interest(87, mens_en_gedrag).
area_of_interest(92, mens_en_gedrag).
area_of_interest(97, mens_en_gedrag).
area_of_interest(98, mens_en_gedrag).
area_of_interest(100, mens_en_gedrag).
area_of_interest(101, mens_en_gedrag).
area_of_interest(106, mens_en_gedrag).
area_of_interest(110, mens_en_gedrag).
area_of_interest(111, mens_en_gedrag).
area_of_interest(114, mens_en_gedrag).
area_of_interest(120, mens_en_gedrag).
area_of_interest(125, mens_en_gedrag).
area_of_interest(128, mens_en_gedrag).

% recht_ecenomie_en_bestuur
area_of_interest(11, recht_ecenomie_en_bestuur).
area_of_interest(16, recht_ecenomie_en_bestuur).
area_of_interest(24, recht_ecenomie_en_bestuur).
area_of_interest(27, recht_ecenomie_en_bestuur).
area_of_interest(28, recht_ecenomie_en_bestuur).
area_of_interest(36, recht_ecenomie_en_bestuur).
area_of_interest(38, recht_ecenomie_en_bestuur).
area_of_interest(40, recht_ecenomie_en_bestuur).
area_of_interest(42, recht_ecenomie_en_bestuur).
area_of_interest(46, recht_ecenomie_en_bestuur).
area_of_interest(65, recht_ecenomie_en_bestuur).
area_of_interest(67, recht_ecenomie_en_bestuur).
area_of_interest(69, recht_ecenomie_en_bestuur).
area_of_interest(83, recht_ecenomie_en_bestuur).
area_of_interest(104, recht_ecenomie_en_bestuur).
area_of_interest(107, recht_ecenomie_en_bestuur).
area_of_interest(109, recht_ecenomie_en_bestuur).
area_of_interest(121, recht_ecenomie_en_bestuur).

% informatietechnologie
area_of_interest(24, informatietechnologie).
area_of_interest(39, informatietechnologie).
area_of_interest(49, informatietechnologie).
area_of_interest(62, informatietechnologie).
area_of_interest(63, informatietechnologie).
area_of_interest(64, informatietechnologie).
area_of_interest(76, informatietechnologie).
area_of_interest(85, informatietechnologie).
area_of_interest(99, informatietechnologie).

% natuur
area_of_interest(54, natuur).
area_of_interest(59, natuur).
area_of_interest(70, natuur).
area_of_interest(124, natuur).