% mens_dier_en_gezondheid
area_of_interest(21, mens_dier_en_gezondheid).
area_of_interest(24, mens_dier_en_gezondheid).
area_of_interest(43, mens_dier_en_gezondheid).
area_of_interest(47, mens_dier_en_gezondheid).
area_of_interest(117, mens_dier_en_gezondheid).

% mens_en_gedrag
area_of_interest(4, mens_en_gedrag).
area_of_interest(8, mens_en_gedrag).
area_of_interest(10, mens_en_gedrag).
area_of_interest(14, mens_en_gedrag).
area_of_interest(15, mens_en_gedrag).
area_of_interest(18, mens_en_gedrag).
area_of_interest(19, mens_en_gedrag).
area_of_interest(20, mens_en_gedrag).
area_of_interest(21, mens_en_gedrag).
area_of_interest(24, mens_en_gedrag).
area_of_interest(25, mens_en_gedrag).
area_of_interest(26, mens_en_gedrag).
area_of_interest(29, mens_en_gedrag).
area_of_interest(30, mens_en_gedrag).
area_of_interest(31, mens_en_gedrag).
area_of_interest(38, mens_en_gedrag).
area_of_interest(39, mens_en_gedrag).
area_of_interest(50, mens_en_gedrag).
area_of_interest(68, mens_en_gedrag).
area_of_interest(73, mens_en_gedrag).
area_of_interest(76, mens_en_gedrag).
area_of_interest(82, mens_en_gedrag).
area_of_interest(87, mens_en_gedrag).
area_of_interest(92, mens_en_gedrag).
area_of_interest(97, mens_en_gedrag).
area_of_interest(98, mens_en_gedrag).
area_of_interest(100, mens_en_gedrag).
area_of_interest(101, mens_en_gedrag).
area_of_interest(106, mens_en_gedrag).
area_of_interest(110, mens_en_gedrag).
area_of_interest(111, mens_en_gedrag).
area_of_interest(114, mens_en_gedrag).
area_of_interest(120, mens_en_gedrag).
area_of_interest(125, mens_en_gedrag).
area_of_interest(128, mens_en_gedrag).

% recht_economie_en_bestuur
area_of_interest(11, recht_economie_en_bestuur).
area_of_interest(16, recht_economie_en_bestuur).
area_of_interest(24, recht_economie_en_bestuur).
area_of_interest(27, recht_economie_en_bestuur).
area_of_interest(28, recht_economie_en_bestuur).
area_of_interest(36, recht_economie_en_bestuur).
area_of_interest(38, recht_economie_en_bestuur).
area_of_interest(40, recht_economie_en_bestuur).
area_of_interest(42, recht_economie_en_bestuur).
area_of_interest(46, recht_economie_en_bestuur).
area_of_interest(65, recht_economie_en_bestuur).
area_of_interest(67, recht_economie_en_bestuur).
area_of_interest(69, recht_economie_en_bestuur).
area_of_interest(83, recht_economie_en_bestuur).
area_of_interest(104, recht_economie_en_bestuur).
area_of_interest(107, recht_economie_en_bestuur).
area_of_interest(109, recht_economie_en_bestuur).
area_of_interest(121, recht_economie_en_bestuur).

% informatietechnologie
area_of_interest(24, informatietechnologie).
area_of_interest(39, informatietechnologie).
area_of_interest(49, informatietechnologie).
area_of_interest(62, informatietechnologie).
area_of_interest(63, informatietechnologie).
area_of_interest(64, informatietechnologie).
area_of_interest(76, informatietechnologie).
area_of_interest(85, informatietechnologie).
area_of_interest(99, informatietechnologie).

% natuur
area_of_interest(54, natuur).
area_of_interest(59, natuur).
area_of_interest(70, natuur).
area_of_interest(124, natuur).

% aarde_en_mileu
area_of_interest(1, aarde_en_mileu).
area_of_interest(2, aarde_en_mileu).
area_of_interest(3, aarde_en_mileu).
area_of_interest(31, aarde_en_mileu).
area_of_interest(32, aarde_en_mileu).
area_of_interest(34, aarde_en_mileu).
area_of_interest(35, aarde_en_mileu).
area_of_interest(37, aarde_en_mileu).
area_of_interest(38, aarde_en_mileu).
area_of_interest(40, aarde_en_mileu).
area_of_interest(52, aarde_en_mileu).
area_of_interest(56, aarde_en_mileu).
area_of_interest(59, aarde_en_mileu).
area_of_interest(66, aarde_en_mileu).
area_of_interest(70, aarde_en_mileu).
area_of_interest(86, aarde_en_mileu).
area_of_interest(90, aarde_en_mileu).
area_of_interest(91, aarde_en_mileu).
area_of_interest(94, aarde_en_mileu).
area_of_interest(96, aarde_en_mileu).
area_of_interest(103, aarde_en_mileu).
area_of_interest(112, aarde_en_mileu).
area_of_interest(116, aarde_en_mileu).
area_of_interest(118, aarde_en_mileu).
area_of_interest(124, aarde_en_mileu).

% kunst_cultuur_en_geschiedenis
area_of_interest(5, kunst_cultuur_en_geschiedenis).
area_of_interest(7, kunst_cultuur_en_geschiedenis).
area_of_interest(9, kunst_cultuur_en_geschiedenis).
area_of_interest(10, kunst_cultuur_en_geschiedenis).
area_of_interest(14, kunst_cultuur_en_geschiedenis).
area_of_interest(17, kunst_cultuur_en_geschiedenis).
area_of_interest(23, kunst_cultuur_en_geschiedenis).
area_of_interest(25, kunst_cultuur_en_geschiedenis).
area_of_interest(26, kunst_cultuur_en_geschiedenis).
area_of_interest(38, kunst_cultuur_en_geschiedenis).
area_of_interest(40, kunst_cultuur_en_geschiedenis).
area_of_interest(41, kunst_cultuur_en_geschiedenis).
area_of_interest(45, kunst_cultuur_en_geschiedenis).
area_of_interest(48, kunst_cultuur_en_geschiedenis).
area_of_interest(50, kunst_cultuur_en_geschiedenis).
area_of_interest(53, kunst_cultuur_en_geschiedenis).
area_of_interest(55, kunst_cultuur_en_geschiedenis).
area_of_interest(58, kunst_cultuur_en_geschiedenis).
area_of_interest(60, kunst_cultuur_en_geschiedenis).
area_of_interest(61, kunst_cultuur_en_geschiedenis).
area_of_interest(67, kunst_cultuur_en_geschiedenis).
area_of_interest(69, kunst_cultuur_en_geschiedenis).
area_of_interest(74, kunst_cultuur_en_geschiedenis).
area_of_interest(75, kunst_cultuur_en_geschiedenis).
area_of_interest(76, kunst_cultuur_en_geschiedenis).
area_of_interest(77, kunst_cultuur_en_geschiedenis).
area_of_interest(80, kunst_cultuur_en_geschiedenis).
area_of_interest(83, kunst_cultuur_en_geschiedenis).
area_of_interest(84, kunst_cultuur_en_geschiedenis).
area_of_interest(85, kunst_cultuur_en_geschiedenis).
area_of_interest(88, kunst_cultuur_en_geschiedenis).
area_of_interest(89, kunst_cultuur_en_geschiedenis).
area_of_interest(93, kunst_cultuur_en_geschiedenis).
area_of_interest(97, kunst_cultuur_en_geschiedenis).
area_of_interest(104, kunst_cultuur_en_geschiedenis).
area_of_interest(105, kunst_cultuur_en_geschiedenis).
area_of_interest(108, kunst_cultuur_en_geschiedenis).
area_of_interest(120, kunst_cultuur_en_geschiedenis).
area_of_interest(122, kunst_cultuur_en_geschiedenis).
area_of_interest(123, kunst_cultuur_en_geschiedenis).

% talen_en_cultuur_communicatie
area_of_interest(7, talen_en_cultuur_communicatie).
area_of_interest(10, talen_en_cultuur_communicatie).
area_of_interest(14, talen_en_cultuur_communicatie).
area_of_interest(17, talen_en_cultuur_communicatie).
area_of_interest(22, talen_en_cultuur_communicatie).
area_of_interest(23, talen_en_cultuur_communicatie).
area_of_interest(33, talen_en_cultuur_communicatie).
area_of_interest(38, talen_en_cultuur_communicatie).
area_of_interest(40, talen_en_cultuur_communicatie).
area_of_interest(41, talen_en_cultuur_communicatie).
area_of_interest(45, talen_en_cultuur_communicatie).
area_of_interest(48, talen_en_cultuur_communicatie).
area_of_interest(49, talen_en_cultuur_communicatie).
area_of_interest(60, talen_en_cultuur_communicatie).
area_of_interest(61, talen_en_cultuur_communicatie).
area_of_interest(67, talen_en_cultuur_communicatie).
area_of_interest(69, talen_en_cultuur_communicatie).
area_of_interest(71, talen_en_cultuur_communicatie).
area_of_interest(72, talen_en_cultuur_communicatie).
area_of_interest(77, talen_en_cultuur_communicatie).
area_of_interest(78, talen_en_cultuur_communicatie).
area_of_interest(79, talen_en_cultuur_communicatie).
area_of_interest(80, talen_en_cultuur_communicatie).
area_of_interest(81, talen_en_cultuur_communicatie).
area_of_interest(83, talen_en_cultuur_communicatie).
area_of_interest(84, talen_en_cultuur_communicatie).
area_of_interest(85, talen_en_cultuur_communicatie).
area_of_interest(88, talen_en_cultuur_communicatie).
area_of_interest(89, talen_en_cultuur_communicatie).
area_of_interest(97, talen_en_cultuur_communicatie).
area_of_interest(115, talen_en_cultuur_communicatie).
area_of_interest(119, talen_en_cultuur_communicatie).
area_of_interest(120, talen_en_cultuur_communicatie).

% religie_filosofie_en_ethiek
area_of_interest(5, religie_filosofie_en_ethiek).
area_of_interest(7, religie_filosofie_en_ethiek).
area_of_interest(38, religie_filosofie_en_ethiek).
area_of_interest(40, religie_filosofie_en_ethiek).
area_of_interest(44, religie_filosofie_en_ethiek).
area_of_interest(54, religie_filosofie_en_ethiek).
area_of_interest(58, religie_filosofie_en_ethiek).
area_of_interest(71, religie_filosofie_en_ethiek).
area_of_interest(88, religie_filosofie_en_ethiek).
area_of_interest(89, religie_filosofie_en_ethiek).
area_of_interest(102, religie_filosofie_en_ethiek).
area_of_interest(104, religie_filosofie_en_ethiek).
area_of_interest(108, religie_filosofie_en_ethiek).
area_of_interest(123, religie_filosofie_en_ethiek).



