area_of_interest("Mens, dier en gezondheid", mens_dier_en_gezondheid).
area_of_interest("Mens en gedrag", mens_en_gedrag).
area_of_interest("Recht, economie en bestuur", recht_economie_en_bestuur).
area_of_interest("Aarde en mileu", aarde_en_mileu).
area_of_interest("Informatietechnologie", informatietechnologie).
area_of_interest("Natuur", natuur).
area_of_interest("Kunst, cultuur en geschiedenis", kunst_cultuur_en_geschiedenis).
area_of_interest("Talen en culturen, communicatie", talen_en_cultuur_communicatie).
area_of_interest("Religie, filosofie en ethiek", religie_filosofie_en_ethiek).

% mens_dier_en_gezondheid
is_in_area(21, mens_dier_en_gezondheid).
is_in_area(24, mens_dier_en_gezondheid).
is_in_area(43, mens_dier_en_gezondheid).
is_in_area(47, mens_dier_en_gezondheid).
is_in_area(117, mens_dier_en_gezondheid).

% mens_en_gedrag
is_in_area(4, mens_en_gedrag).
is_in_area(8, mens_en_gedrag).
is_in_area(10, mens_en_gedrag).
is_in_area(14, mens_en_gedrag).
is_in_area(15, mens_en_gedrag).
is_in_area(18, mens_en_gedrag).
is_in_area(19, mens_en_gedrag).
is_in_area(20, mens_en_gedrag).
is_in_area(21, mens_en_gedrag).
is_in_area(24, mens_en_gedrag).
is_in_area(25, mens_en_gedrag).
is_in_area(26, mens_en_gedrag).
is_in_area(29, mens_en_gedrag).
is_in_area(30, mens_en_gedrag).
is_in_area(31, mens_en_gedrag).
is_in_area(38, mens_en_gedrag).
is_in_area(39, mens_en_gedrag).
is_in_area(50, mens_en_gedrag).
is_in_area(68, mens_en_gedrag).
is_in_area(73, mens_en_gedrag).
is_in_area(76, mens_en_gedrag).
is_in_area(82, mens_en_gedrag).
is_in_area(87, mens_en_gedrag).
is_in_area(92, mens_en_gedrag).
is_in_area(97, mens_en_gedrag).
is_in_area(98, mens_en_gedrag).
is_in_area(100, mens_en_gedrag).
is_in_area(101, mens_en_gedrag).
is_in_area(106, mens_en_gedrag).
is_in_area(110, mens_en_gedrag).
is_in_area(111, mens_en_gedrag).
is_in_area(114, mens_en_gedrag).
is_in_area(120, mens_en_gedrag).
is_in_area(125, mens_en_gedrag).
is_in_area(128, mens_en_gedrag).

% recht_economie_en_bestuur
is_in_area(11, recht_economie_en_bestuur).
is_in_area(16, recht_economie_en_bestuur).
is_in_area(24, recht_economie_en_bestuur).
is_in_area(27, recht_economie_en_bestuur).
is_in_area(28, recht_economie_en_bestuur).
is_in_area(36, recht_economie_en_bestuur).
is_in_area(38, recht_economie_en_bestuur).
is_in_area(40, recht_economie_en_bestuur).
is_in_area(42, recht_economie_en_bestuur).
is_in_area(46, recht_economie_en_bestuur).
is_in_area(65, recht_economie_en_bestuur).
is_in_area(67, recht_economie_en_bestuur).
is_in_area(69, recht_economie_en_bestuur).
is_in_area(83, recht_economie_en_bestuur).
is_in_area(104, recht_economie_en_bestuur).
is_in_area(107, recht_economie_en_bestuur).
is_in_area(109, recht_economie_en_bestuur).
is_in_area(121, recht_economie_en_bestuur).

% informatietechnologie
is_in_area(24, informatietechnologie).
is_in_area(39, informatietechnologie).
is_in_area(49, informatietechnologie).
is_in_area(62, informatietechnologie).
is_in_area(63, informatietechnologie).
is_in_area(64, informatietechnologie).
is_in_area(76, informatietechnologie).
is_in_area(85, informatietechnologie).
is_in_area(99, informatietechnologie).

% natuur
is_in_area(54, natuur).
is_in_area(59, natuur).
is_in_area(70, natuur).
is_in_area(124, natuur).

% aarde_en_mileu
is_in_area(1, aarde_en_mileu).
is_in_area(2, aarde_en_mileu).
is_in_area(3, aarde_en_mileu).
is_in_area(31, aarde_en_mileu).
is_in_area(32, aarde_en_mileu).
is_in_area(34, aarde_en_mileu).
is_in_area(35, aarde_en_mileu).
is_in_area(37, aarde_en_mileu).
is_in_area(38, aarde_en_mileu).
is_in_area(40, aarde_en_mileu).
is_in_area(52, aarde_en_mileu).
is_in_area(56, aarde_en_mileu).
is_in_area(59, aarde_en_mileu).
is_in_area(66, aarde_en_mileu).
is_in_area(70, aarde_en_mileu).
is_in_area(86, aarde_en_mileu).
is_in_area(90, aarde_en_mileu).
is_in_area(91, aarde_en_mileu).
is_in_area(94, aarde_en_mileu).
is_in_area(96, aarde_en_mileu).
is_in_area(103, aarde_en_mileu).
is_in_area(112, aarde_en_mileu).
is_in_area(116, aarde_en_mileu).
is_in_area(118, aarde_en_mileu).
is_in_area(124, aarde_en_mileu).

% kunst_cultuur_en_geschiedenis
is_in_area(5, kunst_cultuur_en_geschiedenis).
is_in_area(7, kunst_cultuur_en_geschiedenis).
is_in_area(9, kunst_cultuur_en_geschiedenis).
is_in_area(10, kunst_cultuur_en_geschiedenis).
is_in_area(14, kunst_cultuur_en_geschiedenis).
is_in_area(17, kunst_cultuur_en_geschiedenis).
is_in_area(23, kunst_cultuur_en_geschiedenis).
is_in_area(25, kunst_cultuur_en_geschiedenis).
is_in_area(26, kunst_cultuur_en_geschiedenis).
is_in_area(38, kunst_cultuur_en_geschiedenis).
is_in_area(40, kunst_cultuur_en_geschiedenis).
is_in_area(41, kunst_cultuur_en_geschiedenis).
is_in_area(45, kunst_cultuur_en_geschiedenis).
is_in_area(48, kunst_cultuur_en_geschiedenis).
is_in_area(50, kunst_cultuur_en_geschiedenis).
is_in_area(53, kunst_cultuur_en_geschiedenis).
is_in_area(55, kunst_cultuur_en_geschiedenis).
is_in_area(58, kunst_cultuur_en_geschiedenis).
is_in_area(60, kunst_cultuur_en_geschiedenis).
is_in_area(61, kunst_cultuur_en_geschiedenis).
is_in_area(67, kunst_cultuur_en_geschiedenis).
is_in_area(69, kunst_cultuur_en_geschiedenis).
is_in_area(74, kunst_cultuur_en_geschiedenis).
is_in_area(75, kunst_cultuur_en_geschiedenis).
is_in_area(76, kunst_cultuur_en_geschiedenis).
is_in_area(77, kunst_cultuur_en_geschiedenis).
is_in_area(80, kunst_cultuur_en_geschiedenis).
is_in_area(83, kunst_cultuur_en_geschiedenis).
is_in_area(84, kunst_cultuur_en_geschiedenis).
is_in_area(85, kunst_cultuur_en_geschiedenis).
is_in_area(88, kunst_cultuur_en_geschiedenis).
is_in_area(89, kunst_cultuur_en_geschiedenis).
is_in_area(93, kunst_cultuur_en_geschiedenis).
is_in_area(97, kunst_cultuur_en_geschiedenis).
is_in_area(104, kunst_cultuur_en_geschiedenis).
is_in_area(105, kunst_cultuur_en_geschiedenis).
is_in_area(108, kunst_cultuur_en_geschiedenis).
is_in_area(120, kunst_cultuur_en_geschiedenis).
is_in_area(122, kunst_cultuur_en_geschiedenis).
is_in_area(123, kunst_cultuur_en_geschiedenis).

% talen_en_cultuur_communicatie
is_in_area(7, talen_en_cultuur_communicatie).
is_in_area(10, talen_en_cultuur_communicatie).
is_in_area(14, talen_en_cultuur_communicatie).
is_in_area(17, talen_en_cultuur_communicatie).
is_in_area(22, talen_en_cultuur_communicatie).
is_in_area(23, talen_en_cultuur_communicatie).
is_in_area(33, talen_en_cultuur_communicatie).
is_in_area(38, talen_en_cultuur_communicatie).
is_in_area(40, talen_en_cultuur_communicatie).
is_in_area(41, talen_en_cultuur_communicatie).
is_in_area(45, talen_en_cultuur_communicatie).
is_in_area(48, talen_en_cultuur_communicatie).
is_in_area(49, talen_en_cultuur_communicatie).
is_in_area(60, talen_en_cultuur_communicatie).
is_in_area(61, talen_en_cultuur_communicatie).
is_in_area(67, talen_en_cultuur_communicatie).
is_in_area(69, talen_en_cultuur_communicatie).
is_in_area(71, talen_en_cultuur_communicatie).
is_in_area(72, talen_en_cultuur_communicatie).
is_in_area(77, talen_en_cultuur_communicatie).
is_in_area(78, talen_en_cultuur_communicatie).
is_in_area(79, talen_en_cultuur_communicatie).
is_in_area(80, talen_en_cultuur_communicatie).
is_in_area(81, talen_en_cultuur_communicatie).
is_in_area(83, talen_en_cultuur_communicatie).
is_in_area(84, talen_en_cultuur_communicatie).
is_in_area(85, talen_en_cultuur_communicatie).
is_in_area(88, talen_en_cultuur_communicatie).
is_in_area(89, talen_en_cultuur_communicatie).
is_in_area(97, talen_en_cultuur_communicatie).
is_in_area(115, talen_en_cultuur_communicatie).
is_in_area(119, talen_en_cultuur_communicatie).
is_in_area(120, talen_en_cultuur_communicatie).

% religie_filosofie_en_ethiek
is_in_area(5, religie_filosofie_en_ethiek).
is_in_area(7, religie_filosofie_en_ethiek).
is_in_area(38, religie_filosofie_en_ethiek).
is_in_area(40, religie_filosofie_en_ethiek).
is_in_area(44, religie_filosofie_en_ethiek).
is_in_area(54, religie_filosofie_en_ethiek).
is_in_area(58, religie_filosofie_en_ethiek).
is_in_area(71, religie_filosofie_en_ethiek).
is_in_area(88, religie_filosofie_en_ethiek).
is_in_area(89, religie_filosofie_en_ethiek).
is_in_area(102, religie_filosofie_en_ethiek).
is_in_area(104, religie_filosofie_en_ethiek).
is_in_area(108, religie_filosofie_en_ethiek).
is_in_area(123, religie_filosofie_en_ethiek).



