minor(aarde_klimaat_en_leven,1).
minor(aarde_water_en_milieu,2).
minor(aardoppervlak_en_landvormen,3).
minor(algemene_sociale_wetenschappen,4).
minor(antieke_cultuur,5).
minor(applied_data_science,6).
minor(arabisch,7).
minor(arbeids_en_organisatiepsychologie,8).
minor(archaeology,9).
minor(art_the_senses_and_society,10).
minor(bestuurs_en_organisatiewetenschap_algemeen,11).
minor(biologie,12).
minor(biomedische_wetenschappen,13).
minor(brains_bodies_cognitie_en_emotie_in_de_geesteswetenschappen,14).
minor(burgerschap_identiteit_en_mondialisering,15).
minor(business_economics,16).
minor(celtic_languages_and_culture,17).
minor(child_and_adolescent_relationships_and_development_,18).
minor(citizenship_identity_and_globalisation,19).
minor(cognitie,20).
minor(cognitive_and_clinical_neuroscience,21).
minor(communicatie_en_informatiewetenschappen,22).
minor(comparative_media_studies,23).
minor(complex_systems,24).
minor(conflict_studies,25).
minor(creative_cities,26).
minor(criminologie_voor_studenten_rechtsgeleerdheid,27).
minor(criminologie_voor_studenten_sociale_wetenschappen,28).
minor(culturele_diversiteit,29).
minor(cultuur_communicatie_en_mediastudies,30).
minor(deltametropool_planningsvraagstukken_en_mobiliteit,31).
minor(development_geography,32).
minor(duitse_taal_en_cultuur,33).
minor(duurzaam_ondernemen_en_innovatie,34).
minor(duurzame_ontwikkeling,35).
minor(economics,36).
minor(economische_geografie,37).
minor(educatieve_minor_alfa,38).
minor(educatieve_minor_bèta,39).
minor(educatieve_minor_gamma,40).
minor(english_language_and_culture,41).
minor(entrepreneurship,42).
minor(entrepreneurship_in_life_sciences_and_health,43).
minor(ethics_in_modern_society,44).
minor(europa_in_de_vroegmoderne_tijd,45).
minor(european_governance,46).
minor(farmaceutische_wetenschappen,47).
minor(franse_taal_en_cultuur,48).
minor(game_studies,49).
minor(gender_studies,50).
minor(geneesmiddelonderzoek,51).
minor(geologie_van_de_vaste_aarde,52).
minor(geschiedenis,53).
minor(geschiedenis_en_filosofie_van_de_natuurwetenschappen,54).
minor(global_asia,55).
minor(global_change,56).
minor(globalisering_en_mondiale_ongelijkheid,57).
minor(goede_ware_schone,58).
minor(governance_for_sustainable_development,59).
minor(griekse_taal_cultuur_in_de_europese_traditie,60).
minor(identiteit_en_diversiteit_in_nederlandse_taal_en_cultuur,61).
minor(informatica,62).
minor(informatica_voor_hbostudenten,63).
minor(informatiekunde,64).
minor(inleiding_in_het_recht,65).
minor(innovatiewetenschappen,66).
minor(interculturele_communicatie,67).
minor(international_perspectives_on_youth_and_education,68).
minor(internationale_betrekkingen,69).
minor(interuniversitaire_minor_porous_media,70).
minor(islam,71).
minor(italiaanse_taal_en_cultuur,72).
minor(jeugdcriminaliteit_en_jeugdbescherming,73).
minor(kunst_cultuur_en_maatschappij,74).
minor(kunstgeschiedenis,75).
minor(kunstmatige_intelligentie,76).
minor(latijnse_taal_cultuur_in_de_europese_traditie,77).
minor(linguistics,78).
minor(literature_in_conflict,79).
minor(literatuurwetenschap,80).
minor(logopediewetenschap,81).
minor(maatschappelijke_opvoedingsvraagstukken,82).
minor(macht_en_onmacht_van_de_markt,83).
minor(media_en_cultuur,84).
minor(media_data_and_platform_studies,85).
minor(meteorologie_fysische_oceanografie_en_klimaat,86).
minor(methods_and_statistics_in_the_social_and_behavioural_sciences_,87).
minor(middle_ages,88).
minor(middle_eastern_studies,89).
minor(milieumaatschappijwetenschappen,90).
minor(milieunatuurwetenschappen,91).
minor(multicultural_society,92).
minor(muziekwetenschap,93).
minor(nationale_geoinformatie_minor,94).
minor(natuurkunde,95).
minor(natuurkunde_van_de_vaste_aarde,96).
minor(nederlands_als_tweede_taal_,97).
minor(onderwijswetenschappen,98).
minor(organisatie_en_informatie_voor_hbostudenten,99).
minor(orthopedagogiek,100).
minor(persoonlijkheid_en_relaties,101).
minor(philosophy_politics_and_economics,102).
minor(planologie,103).
minor(politiek_tussen_nationale_staat_en_mondiale_samenleving,104).
minor(postcolonial_studies,105).
minor(psychosociale_problemen,106).
minor(recht_innovatie_technologie,107).
minor(religiewetenschappen,108).
minor(sociaal_ondernemerschap,109).
minor(social_neuroscience,110).
minor(social_policy_and_public_health,111).
minor(sociale_geografie,112).
minor(sociology_and_social_research,113).
minor(sociology_contemporary_social_problems,114).
minor(spaanse_taal_en_cultuur,115).
minor(stadsgeografie,116).
minor(structuurbiologie,117).
minor(sustainable_energy,118).
minor(taalontwikkeling,119).
minor(talen_en_educatie,120).
minor(theorie_van_het_recht,121).
minor(transatlantic_studies,122).
minor(wat_is_de_mens,123).
minor(water_klimaat_ecosystemen,124).
minor(wellbeing_by_design_behavioral_foundations_and_public_policy,125).
minor(wiskunde_voor_natuurkundigen,126).
minor(wiskunde_voor_nietnatuurkundigen,127).
minor(youth_studies,128).
