% dutch
language(1, dutch).
language(2, dutch).
language(3, dutch).
language(4, dutch).
language(5, dutch).
language(7, dutch).
language(8, dutch).
language(11, dutch).
language(12, dutch).
language(13, dutch).
language(14, dutch).
language(15, dutch).
language(17, dutch).
language(19, dutch).
language(20, dutch).
language(22, dutch).
language(24, dutch).
language(27, dutch).
language(28, dutch).
language(29, dutch).
language(30, dutch).
language(31, dutch).
language(32, dutch).
language(33, dutch).
language(34, dutch).
language(35, dutch).
language(37, dutch).
language(38, dutch).
language(39, dutch).
language(40, dutch).
language(42, dutch).
language(45, dutch).
language(47, dutch).
language(48, dutch).
language(49, dutch).
language(50, dutch).
language(51, dutch).
language(52, dutch).
language(53, dutch).
language(54, dutch).
language(56, dutch).
language(57, dutch).
language(58, dutch).
language(59, dutch).
language(60, dutch).
language(61, dutch).
language(62, dutch).
language(63, dutch).
language(64, dutch).
language(65, dutch).
language(66, dutch).
language(67, dutch).
language(68, dutch).
language(69, dutch).
language(70, dutch).
language(71, dutch).
language(72, dutch).
language(73, dutch).
language(74, dutch).
language(75, dutch).
language(76, dutch).
language(77, dutch).
language(78, dutch).
language(79, dutch).
language(80, dutch).
language(81, dutch).
language(82, dutch).
language(83, dutch).
language(84, dutch).
language(85, dutch).
language(86, dutch).
language(90, dutch).
language(91, dutch).
language(93, dutch).
language(94, dutch).
language(95, dutch).
language(96, dutch).
language(97, dutch).
language(98, dutch).
language(99, dutch).
language(100, dutch).
language(101, dutch).
language(103, dutch).
language(104, dutch).
language(106, dutch).
language(107, dutch).
language(108, dutch).
language(109, dutch).
language(112, dutch).
language(115, dutch).
language(116, dutch).
language(117, dutch).
language(119, dutch).
language(120, dutch).
language(121, dutch).
language(123, dutch).
language(124, dutch).
language(126, dutch).
language(127, dutch).

% english
language(6, english).
language(9, english).
language(10, english).
language(16, english).
language(17, english).
language(18, english).
language(19, english).
language(21, english).
language(23, english).
language(25, english).
language(26, english).
language(34, english).
language(36, english).
language(41, english).
language(42, english).
language(43, english).
language(44, english).
language(46, english).
language(49, english).
language(55, english).
language(56, english).
language(59, english).
language(66, english).
language(68, english).
language(78, english).
language(85, english).
language(87, english).
language(88, english).
language(89, english).
language(92, english).
language(102, english).
language(105, english).
language(110, english).
language(111, english).
language(113, english).
language(114, english).
language(118, english).
language(122, english).
language(125, english).
language(128, english).


